In [77]:
context_length = 32


In [57]:
from tokenizer import Tokenizer

tokenizer = Tokenizer("tokenizer.json")

In [58]:
##Embeeding yani Sözlük Anlamlarının Sayısal Değerleri

In [59]:
the_1 = 0.1 #parlaklık ekseni
the_2 = 0.4 #sertlik ekseni
the_3 = 0.0 #mavilik ekseni
the_4 = 0.0 #kırmızılık ekseni
the_5 = 0.7 #yeşillik ekseni

capital_1 = 0.0 #parlaklık ekseni
capital_2 = 0.2 #sertlik ekseni
capital_3 = 0.24 #mavilik ekseni
capital_4 = 0.3 #kırmızılık ekseni
capital_5 = 0.1 #yeşillik ekseni
#Kelimeler 5 boyutlu uzayda incelenir

In [60]:

dict_v2 = {
    "the": [0.1, 0.0, 0.0, 0.0],
    "capital": [0.4, 0.2, 0.04, 0.3],
    "of": [0.0, 0.24, 0.02, 0.01],
    "united": [0.0, 0.0, 0.03, 0.01],
    "states": [0.0, 0.0, 0.0, 0.0]
}

dict_v2["the"], dict_v2["capital"], dict_v2["of"], dict_v2["united"], dict_v2["states"]

([0.1, 0.0, 0.0, 0.0],
 [0.4, 0.2, 0.04, 0.3],
 [0.0, 0.24, 0.02, 0.01],
 [0.0, 0.0, 0.03, 0.01],
 [0.0, 0.0, 0.0, 0.0])

In [61]:
import plotly.graph_objects as go
import plotly.offline as pyo

data = [
    go.Scatter3d(
        x=[0.1, 0.4, 0.0, 0.0, 0.0],
        y=[0.0, 0.2, 0.24, 0.0, 0.0],
        z=[0.0, 0.0, 0.0, 0.03, 0.0],
        mode="markers+text",
        marker=dict(
            size=10,
            color="red",
        ),
        text=["the", "capital", "of", "united", "states"],
        hoverinfo="text"
    )
]

layout = go.Layout(
    scene=dict(
        xaxis_title="Sertlik",
        yaxis_title="Parlaklık",
        zaxis_title="Kırmızılık",
    ),
    title="Sözlük V1",
)

fig = go.Figure(data=data, layout=layout)
pyo.plot(fig)

'temp-plot.html'

In [90]:
import plotly.graph_objects as go
import plotly.offline as pyo

def plot_dots(sentences_data, title):
    data = [
        go.Scatter3d(
            x=sentence_data["words"][:, 0],
            y=sentence_data["words"][:, 1],
            z=sentence_data["words"][:, 2],
            marker=dict(
                size=10,
                color=sentence_data["color"],
            ),
            text=sentence_data["labels"],
            hoverinfo="text",
        )   for sentence_data in sentences_data
    ]


    layout = go.Layout(
    scene=dict(
        xaxis_title="Sertlik",
        yaxis_title="Parlaklık",
        zaxis_title="Kırmızılık",
        ),
        title=title,
    )

    fig = go.Figure(data=data, layout=layout)
    pyo.plot(fig)

In [91]:
import numpy as np

sentences = [
    {
        "words": np.array([
        [0.1, 0.0, 0.0, 0.0],
        [0.4, 0.2, 0.04, 0.3],
        [0.0, 0.24, 0.02, 0.01],
        [0.0, 0.0, 0.03, 0.01],
        [0.0, 0.0, 0.0, 0.0]
        ]),
        "labels": ["the", "capital", "of", "united", "states"],
        "color": "red",
    }
]

plot_dots(sentences, "Sözlük V1")

In [64]:
import torch

embeddings = torch.nn.Embedding(num_embeddings=64, embedding_dim=4)

In [65]:
sentence = "the capital of united states and the capital of france"

In [66]:
tokens = tokenizer.encode(sentence)
tokens = torch.tensor(tokens)
tokens

/var/folders/t_/szm46pqj0zv61p2d4vk_p97m0000gn/T/ipykernel_99160/1339664811.py:2: UserWarning:

To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).



tensor([ 0, 61,  1, 61,  2, 61,  3, 61,  4, 58, 61, 10, 61,  0, 61,  1, 61,  2,
        61,  8])

In [67]:
meanings = embeddings(tokens)
meanings

tensor([[-1.2560,  0.8956,  0.1675,  0.7514],
        [ 0.1643, -0.3161,  0.1285, -0.5277],
        [ 2.4142,  1.0206, -0.4405, -1.7342],
        [ 0.1643, -0.3161,  0.1285, -0.5277],
        [-1.2362,  1.5786, -1.1161,  0.7678],
        [ 0.1643, -0.3161,  0.1285, -0.5277],
        [-0.5882,  2.1189, -0.5422, -2.4593],
        [ 0.1643, -0.3161,  0.1285, -0.5277],
        [-1.1108, -1.1187,  0.7580, -0.4957],
        [-1.5083, -0.7200, -1.1910,  1.3271],
        [ 0.1643, -0.3161,  0.1285, -0.5277],
        [ 0.9912, -0.0586,  1.1788,  0.6222],
        [ 0.1643, -0.3161,  0.1285, -0.5277],
        [-1.2560,  0.8956,  0.1675,  0.7514],
        [ 0.1643, -0.3161,  0.1285, -0.5277],
        [ 2.4142,  1.0206, -0.4405, -1.7342],
        [ 0.1643, -0.3161,  0.1285, -0.5277],
        [-1.2362,  1.5786, -1.1161,  0.7678],
        [ 0.1643, -0.3161,  0.1285, -0.5277],
        [-0.2383, -1.3542,  0.2687,  0.1146]], grad_fn=<EmbeddingBackward0>)

In [68]:
sentence1 = "the dog chased the cat"
sentence2 = "the cat chased the dog"

In [69]:
torch.manual_seed(1)

pos_embeddings = torch.nn.Embedding(num_embeddings=context_length, embedding_dim=4)
pos_meanings = pos_embeddings(torch.tensor([i for i in range(context_length)]))

In [70]:
import math
import torch

def get_position_encoding(context_length, embedding_dim, base=10000, device="cpu"):
    p_embeddings = torch.zeros(context_length, embedding_dim, device=device)
    for pos in range(context_length):
        for i in range(embedding_dim // 2):
            p_embeddings[pos, 2 * i] = math.sin(pos / (base ** (2 * i / embedding_dim)))
            if i + 1 < embedding_dim:
                p_embeddings[pos, 2 * i + 1] = math.cos(pos / (base ** (2 * i + 1 / embedding_dim)))

    return p_embeddings.unsqueeze(0)


In [71]:
import torch

torch.manual_seed(1)
embeddings = torch.nn.Embedding(num_embeddings=64, embedding_dim=4)

In [72]:
meanings_in_context = meanings + pos_meanings

In [89]:
sentences = [
    {
        "words": meanings_in_context.detach().numpy(),
        "labels": tokenizer.tokenize(sentence),
        "color": "red",
    },
]
plot_dots(sentences, "Sentence Context Space")

In [ ]:
def get_rotary_position_encoding(input: torch.Tensor, base=10000, device="cpu"):
    context_length, dimension = input.shape

    assert dimension % 2 == 0, "dimension must be even "
    half_dimension = dimension // 2

    freqs_indices = torch.arange(0, half_dimension, device=device, dtype=torch.float32)

    freqs = 1.0 / (base ** (freqs_indices / dimension))

    positions = torch.arange(0, context_length, device=device, dtype=torch.float32).unsqueeze(1)

    angles = positions * freqs

    sin_angles = torch.sin(angles)
    cos_angles = torch.cos(angles)

    input_even = input[:, :dimension // 2]
    input_odd = input[:, dimension // 2:]

    input_even_rotated = input_even * cos_angles - input_odd * sin_angles
    input_odd_rotated = input_even * sin_angles + input_odd * cos_angles

    input_rotated = torch.empty_like(input)
    input_rotated[:, :dimension // 2] = input_even_rotated
    input_rotated[:, dimension // 2:] = input_odd_rotated

    return input_rotated

In [83]:
torch.manual_seed(1)
random_input = torch.randn(context_length, 4)

pos_rotary_encodings = get_rotary_position_encoding(random_input)
pos_rotary_encodings

tensor([[-1.5256, -0.7502, -1.5256, -0.7502],
        [ 0.7703, -0.4455,  0.7703, -0.4455],
        [ 1.0032,  0.3476,  1.0032,  0.3476],
        [ 0.1878,  1.4736,  0.1878,  1.4736],
        [ 0.9850, -1.1467,  0.9850, -1.1467],
        [-0.3901, -0.1726, -0.3901, -0.1726],
        [ 0.4304,  0.6715,  0.4304,  0.6715],
        [ 0.5704, -0.3877,  0.5704, -0.3877],
        [-0.4295,  0.5046, -0.4295,  0.5046],
        [-0.2444,  0.4010, -0.2444,  0.4010],
        [ 0.0073,  0.1824,  0.0073,  0.1824],
        [ 1.5852,  0.0908,  1.5852,  0.0908],
        [-0.7470,  0.6049, -0.7470,  0.6049],
        [ 0.2025, -1.8238,  0.2025, -1.8238],
        [ 0.2030,  0.7948,  0.2030,  0.7948],
        [ 0.9969,  0.6845,  0.9969,  0.6845],
        [-0.1472,  1.0350, -0.1472,  1.0350],
        [ 1.6668, -0.0093,  1.6668, -0.0093],
        [-1.2130,  0.8516, -1.2130,  0.8516],
        [-0.5151,  1.1106, -0.5151,  1.1106],
        [ 0.3904, -0.7068,  0.3904, -0.7068],
        [ 0.6421,  0.3909,  0.6421

In [84]:
meanings_with_pos_encodings = get_rotary_position_encoding(meanings)

In [86]:
sentences = [
    {
        "words": meanings_with_pos_encodings.detach().numpy(),
        "labels": tokenizer.tokenize(sentence),
        "color": "red",
    },
    {
        "words": meanings.detach().numpy(),
        "labels": tokenizer.tokenize(sentence),
        "color": "blue",
    },
]

plot_dots(sentences, "Sentence Context Space V3 Rotary Encoding")

In [87]:
### MODEL LAST ###

In [ ]:
import torch

from usta_model import UstaModel
from usta_tokenizer import UstaTokenizer

u_tokenizer = UstaTokenizer("tokenizer.json")
model = UstaModel(vocab_size=len(u_tokenizer.vocab), embedding_dim=4, context_length=32)